"""added a vote model for handling upvotes and downvotes

Revision ID: fae20128138e
Revises: 6518dc50627d
Create Date: 2018-05-20 10:26:56.625995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae20128138e'
down_revision = '6518dc50627d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='vote_author_id_fkey'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='vote_pitch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vote_pkey')
    )
    # ### end Alembic commands ###
